# Generated by Django 5.1.2 on 2024-10-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KandiGen', '0003_word_count_alter_usersettings_age_alter_word_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='page_num',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
